### ISSUE TITLE
DeprecationWarning: invalid escape sequence \d

### ISSUE THREAD

**Issue by Skeen** [magenta-aps/service_person_stamdata_udvidet#11]
```
  /usr/local/lib/python3.9/site-packages/service_person_stamdata_udvidet/udvidet_person_stam_data_lokal.py:29: DeprecationWarning: invalid escape sequence \d
```
Her: https://github.com/magenta-aps/service_person_stamdata_udvidet/blob/46569630f6d8e95a10d6b30461af71fcfac9a35c/service_person_stamdata_udvidet/udvidet_person_stam_data_lokal.py#L50

Der bør nok være dobbelt escape i regex fordi det er en `r`-string

**Comment by heiniovason** [comment]
Det er tilsyneladende et problem(fejler), hvis man tilføjer dobbelt escape til [udtrykket](https://github.com/magenta-aps/service_person_stamdata_udvidet/blob/787f6a6bd39a935847cdee1cbbcabde85d261892/service_person_stamdata_udvidet/helpers.py#L91), hvor checket udføres.
